language: node_js
node_js:
  - '6'
cache:
  directories:
    - node_modules
env:
  - PACKAGE=xy-chart
  - PACKAGE=sparkline
  - PACKAGE=histogram
  - PACKAGE=radial-chart
  - PACKAGE=data-table
  - PACKAGE=data-ui-theme
  - PACKAGE=forms
  - PACKAGE=network
  - PACKAGE=core
script:
  - 'cd ./packages/$PACKAGE && npm install && npm run test'
  - 'cd ../../'
  - 'eslint --ignore-path=.eslintignore --ext .js,.jsx ./packages/$PACKAGE'
after_script:
  - 'cat ./packages/$PACKAGE/coverage/lcov.info | ./node_modules/.bin/coveralls'
